name: flutter_parallax
description: A Flutter widget that moves at a different velocity than the main scrolling content
version: 0.0.1
author: Romain Rastel <lets4r@gmail.com>
homepage: https://github.com/letsar/flutter_parallax

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  test: ^0.12.0
  flutter_test:
    sdk: flutter

environment:
  sdk: ">=1.19.0 <2.0.0"
  flutter: ">=0.1.5 <0.3.0"